/* Generated by tools/gen_atomic.py. Do not edit. */

#ifndef NTH_INL_ATOMIC_H
#define NTH_INL_ATOMIC_H

#include <narthex/utils/arch.h>
#include <narthex/utils/compiler.h>
#include <narthex/nth_types.h>

#if NTH_COMPILER_MSVC
    #if NTH_ARCH_UNKNOWN
        #error "narthex: atomics require a 64 bit target on MSVC"
    #endif
    #include <intrin.h>
    #include <string.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif


/* nth_atomic_<op>[_<order>]_<type>
 *
 * The unsuffixed name is sequentially consistent, matching C11 and C++. Weaker
 * orderings are opt-in and visible at the call site:
 *
 *   load                                 _relaxed  _acquire
 *   store                                _relaxed  _release
 *   fetch_add sub and or xor             _relaxed  _acq_rel
 *
 * fetch_* returns the previous value and is defined for integer types only,
 * matching C11, where atomic_fetch_add rejects a floating point operand.
 *
 * Operands must be naturally aligned. consume is not provided: no compiler
 * implements it, all of them promote it to acquire.
 *
 * On MSVC the weaker forms may emit stronger barriers than requested, which is
 * always safe. _ReadWriteBarrier is compiler only, which is sufficient on
 * x86-64 because the hardware already provides acquire and release.
 */

#if NTH_COMPILER_GCC || NTH_COMPILER_CLANG

    #define NTH_ATOMIC_DEFINE_LS(T, SUF, W, IT, ISUF, CT)                       \
        static inline T nth_atomic_load_##SUF(const volatile T *p) {            \
            T r;                                                                \
            __atomic_load(p, &r, __ATOMIC_SEQ_CST);                             \
            return r;                                                           \
        }                                                                       \
        static inline T nth_atomic_load_relaxed_##SUF(const volatile T *p) {    \
            T r;                                                                \
            __atomic_load(p, &r, __ATOMIC_RELAXED);                             \
            return r;                                                           \
        }                                                                       \
        static inline T nth_atomic_load_acquire_##SUF(const volatile T *p) {    \
            T r;                                                                \
            __atomic_load(p, &r, __ATOMIC_ACQUIRE);                             \
            return r;                                                           \
        }                                                                       \
        static inline void nth_atomic_store_##SUF(volatile T *p, T v) {         \
            __atomic_store(p, &v, __ATOMIC_SEQ_CST);                            \
        }                                                                       \
        static inline void nth_atomic_store_relaxed_##SUF(volatile T *p, T v) { \
            __atomic_store(p, &v, __ATOMIC_RELAXED);                            \
        }                                                                       \
        static inline void nth_atomic_store_release_##SUF(volatile T *p, T v) { \
            __atomic_store(p, &v, __ATOMIC_RELEASE);                            \
        }

    #define NTH_ATOMIC_DEFINE_RMW(T, SUF, ISUF, CT, UT)                          \
        static inline T nth_atomic_fetch_add_##SUF(volatile T *p, T v) {         \
            return __atomic_fetch_add(p, v, __ATOMIC_SEQ_CST);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_add_relaxed_##SUF(volatile T *p, T v) { \
            return __atomic_fetch_add(p, v, __ATOMIC_RELAXED);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_add_acq_rel_##SUF(volatile T *p, T v) { \
            return __atomic_fetch_add(p, v, __ATOMIC_ACQ_REL);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_sub_##SUF(volatile T *p, T v) {         \
            return __atomic_fetch_sub(p, v, __ATOMIC_SEQ_CST);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_sub_relaxed_##SUF(volatile T *p, T v) { \
            return __atomic_fetch_sub(p, v, __ATOMIC_RELAXED);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_sub_acq_rel_##SUF(volatile T *p, T v) { \
            return __atomic_fetch_sub(p, v, __ATOMIC_ACQ_REL);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_and_##SUF(volatile T *p, T v) {         \
            return __atomic_fetch_and(p, v, __ATOMIC_SEQ_CST);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_and_relaxed_##SUF(volatile T *p, T v) { \
            return __atomic_fetch_and(p, v, __ATOMIC_RELAXED);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_and_acq_rel_##SUF(volatile T *p, T v) { \
            return __atomic_fetch_and(p, v, __ATOMIC_ACQ_REL);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_or_##SUF(volatile T *p, T v) {          \
            return __atomic_fetch_or(p, v, __ATOMIC_SEQ_CST);                    \
        }                                                                        \
        static inline T nth_atomic_fetch_or_relaxed_##SUF(volatile T *p, T v) {  \
            return __atomic_fetch_or(p, v, __ATOMIC_RELAXED);                    \
        }                                                                        \
        static inline T nth_atomic_fetch_or_acq_rel_##SUF(volatile T *p, T v) {  \
            return __atomic_fetch_or(p, v, __ATOMIC_ACQ_REL);                    \
        }                                                                        \
        static inline T nth_atomic_fetch_xor_##SUF(volatile T *p, T v) {         \
            return __atomic_fetch_xor(p, v, __ATOMIC_SEQ_CST);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_xor_relaxed_##SUF(volatile T *p, T v) { \
            return __atomic_fetch_xor(p, v, __ATOMIC_RELAXED);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_xor_acq_rel_##SUF(volatile T *p, T v) { \
            return __atomic_fetch_xor(p, v, __ATOMIC_ACQ_REL);                   \
        }

#elif NTH_COMPILER_MSVC

    #define NTH_ATOMIC_DEFINE_LS(T, SUF, W, IT, ISUF, CT)                       \
        static inline T nth_atomic_load_##SUF(const volatile T *p) {            \
            IT b;                                                               \
            T r;                                                                \
            b = __iso_volatile_load##W((const volatile IT *)p);                 \
            _ReadWriteBarrier();                                                \
            memcpy(&r, &b, sizeof r);                                           \
            return r;                                                           \
        }                                                                       \
        static inline T nth_atomic_load_relaxed_##SUF(const volatile T *p) {    \
            IT b;                                                               \
            T r;                                                                \
            b = __iso_volatile_load##W((const volatile IT *)p);                 \
            memcpy(&r, &b, sizeof r);                                           \
            return r;                                                           \
        }                                                                       \
        static inline T nth_atomic_load_acquire_##SUF(const volatile T *p) {    \
            IT b;                                                               \
            T r;                                                                \
            b = __iso_volatile_load##W((const volatile IT *)p);                 \
            _ReadWriteBarrier();                                                \
            memcpy(&r, &b, sizeof r);                                           \
            return r;                                                           \
        }                                                                       \
        static inline void nth_atomic_store_##SUF(volatile T *p, T v) {         \
            IT b;                                                               \
            memcpy(&b, &v, sizeof b);                                           \
            (void)_InterlockedExchange##ISUF((volatile CT *)p, (CT)b);          \
        }                                                                       \
        static inline void nth_atomic_store_relaxed_##SUF(volatile T *p, T v) { \
            IT b;                                                               \
            memcpy(&b, &v, sizeof b);                                           \
            __iso_volatile_store##W((volatile IT *)p, b);                       \
        }                                                                       \
        static inline void nth_atomic_store_release_##SUF(volatile T *p, T v) { \
            IT b;                                                               \
            memcpy(&b, &v, sizeof b);                                           \
            _ReadWriteBarrier();                                                \
            __iso_volatile_store##W((volatile IT *)p, b);                       \
        }

    #define NTH_ATOMIC_DEFINE_RMW(T, SUF, ISUF, CT, UT)                          \
        static inline T nth_atomic_fetch_add_##SUF(volatile T *p, T v) {         \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedExchangeAdd##ISUF((volatile CT *)p, x);        \
        }                                                                        \
        static inline T nth_atomic_fetch_add_relaxed_##SUF(volatile T *p, T v) { \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedExchangeAdd##ISUF((volatile CT *)p, x);        \
        }                                                                        \
        static inline T nth_atomic_fetch_add_acq_rel_##SUF(volatile T *p, T v) { \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedExchangeAdd##ISUF((volatile CT *)p, x);        \
        }                                                                        \
        static inline T nth_atomic_fetch_sub_##SUF(volatile T *p, T v) {         \
            const CT x = (CT)(UT)(0 - (UT)v);                                    \
            return (T)_InterlockedExchangeAdd##ISUF((volatile CT *)p, x);        \
        }                                                                        \
        static inline T nth_atomic_fetch_sub_relaxed_##SUF(volatile T *p, T v) { \
            const CT x = (CT)(UT)(0 - (UT)v);                                    \
            return (T)_InterlockedExchangeAdd##ISUF((volatile CT *)p, x);        \
        }                                                                        \
        static inline T nth_atomic_fetch_sub_acq_rel_##SUF(volatile T *p, T v) { \
            const CT x = (CT)(UT)(0 - (UT)v);                                    \
            return (T)_InterlockedExchangeAdd##ISUF((volatile CT *)p, x);        \
        }                                                                        \
        static inline T nth_atomic_fetch_and_##SUF(volatile T *p, T v) {         \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedAnd##ISUF((volatile CT *)p, x);                \
        }                                                                        \
        static inline T nth_atomic_fetch_and_relaxed_##SUF(volatile T *p, T v) { \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedAnd##ISUF((volatile CT *)p, x);                \
        }                                                                        \
        static inline T nth_atomic_fetch_and_acq_rel_##SUF(volatile T *p, T v) { \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedAnd##ISUF((volatile CT *)p, x);                \
        }                                                                        \
        static inline T nth_atomic_fetch_or_##SUF(volatile T *p, T v) {          \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedOr##ISUF((volatile CT *)p, x);                 \
        }                                                                        \
        static inline T nth_atomic_fetch_or_relaxed_##SUF(volatile T *p, T v) {  \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedOr##ISUF((volatile CT *)p, x);                 \
        }                                                                        \
        static inline T nth_atomic_fetch_or_acq_rel_##SUF(volatile T *p, T v) {  \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedOr##ISUF((volatile CT *)p, x);                 \
        }                                                                        \
        static inline T nth_atomic_fetch_xor_##SUF(volatile T *p, T v) {         \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedXor##ISUF((volatile CT *)p, x);                \
        }                                                                        \
        static inline T nth_atomic_fetch_xor_relaxed_##SUF(volatile T *p, T v) { \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedXor##ISUF((volatile CT *)p, x);                \
        }                                                                        \
        static inline T nth_atomic_fetch_xor_acq_rel_##SUF(volatile T *p, T v) { \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedXor##ISUF((volatile CT *)p, x);                \
        }

#else
    #error "narthex: no atomic support known for this compiler"
#endif


NTH_ATOMIC_DEFINE_LS(nth_u8, u8, 8, __int8, 8, char)
NTH_ATOMIC_DEFINE_LS(nth_u16, u16, 16, __int16, 16, short)
NTH_ATOMIC_DEFINE_LS(nth_u32, u32, 32, __int32, , long)
NTH_ATOMIC_DEFINE_LS(nth_u64, u64, 64, __int64, 64, __int64)
NTH_ATOMIC_DEFINE_LS(nth_i8, i8, 8, __int8, 8, char)
NTH_ATOMIC_DEFINE_LS(nth_i16, i16, 16, __int16, 16, short)
NTH_ATOMIC_DEFINE_LS(nth_i32, i32, 32, __int32, , long)
NTH_ATOMIC_DEFINE_LS(nth_i64, i64, 64, __int64, 64, __int64)
NTH_ATOMIC_DEFINE_LS(nth_f32, f32, 32, __int32, , long)
NTH_ATOMIC_DEFINE_LS(nth_f64, f64, 64, __int64, 64, __int64)

NTH_ATOMIC_DEFINE_RMW(nth_u8, u8, 8, char, nth_u8)
NTH_ATOMIC_DEFINE_RMW(nth_u16, u16, 16, short, nth_u16)
NTH_ATOMIC_DEFINE_RMW(nth_u32, u32, , long, nth_u32)
NTH_ATOMIC_DEFINE_RMW(nth_u64, u64, 64, __int64, nth_u64)
NTH_ATOMIC_DEFINE_RMW(nth_i8, i8, 8, char, nth_u8)
NTH_ATOMIC_DEFINE_RMW(nth_i16, i16, 16, short, nth_u16)
NTH_ATOMIC_DEFINE_RMW(nth_i32, i32, , long, nth_u32)
NTH_ATOMIC_DEFINE_RMW(nth_i64, i64, 64, __int64, nth_u64)

#undef NTH_ATOMIC_DEFINE_LS
#undef NTH_ATOMIC_DEFINE_RMW


#ifdef __cplusplus
}
#endif

#endif /* NTH_INL_ATOMIC_H */
