/* Hand maintained. Was generated by tools/gen_atomic.py, which no longer exists:
   add new operations by extending the DEFINE macros below. */

#ifndef NTH_INL_ATOMIC_H
#define NTH_INL_ATOMIC_H

#include <narthex/utils/arch.h>
#include <narthex/utils/compiler.h>
#include <narthex/nth_types.h>

#if NTH_COMPILER_MSVC
    #if NTH_ARCH_UNKNOWN
        #error "narthex: atomics require a 64 bit target on MSVC"
    #endif
    #include <intrin.h>
    #include <string.h>
#endif

#ifdef __cplusplus
extern "C" {
#endif


/* nth_atomic_<op>[_<order>]_<type>
 *
 * The unsuffixed name is sequentially consistent, matching C11 and C++. Weaker
 * orderings are opt-in and visible at the call site:
 *
 *   load                                 _relaxed  _acquire
 *   store                                _relaxed  _release
 *   fetch_add sub and or xor             _relaxed  _acq_rel
 *   cas                                  _relaxed  _acq_rel
 *
 * fetch_* returns the previous value and is defined for integer types only,
 * matching C11, where atomic_fetch_add rejects a floating point operand.
 *
 * cas(p, expected, desired) is compare and swap. It stores desired into *p and
 * returns true when *p equals *expected, otherwise it leaves *p alone, writes
 * the value actually observed into *expected, and returns false. That out
 * parameter is how a losing caller learns which state it lost to.
 *
 * Only the strong form is provided: it never fails spuriously, so it is correct
 * in a one shot transition with no retry loop. The weak form belongs to loops
 * that would absorb a spurious failure, and nothing here needs one yet.
 *
 * cas is integer only. C11 allows it on floating point, but it compares object
 * representations, so a NaN never matches itself and 0.0 never matches -0.0.
 *
 * The failure order is never stronger than the success order, as C11 requires:
 * _acq_rel fails as acquire, because a failed exchange performs no store.
 *
 * Operands must be naturally aligned. consume is not provided: no compiler
 * implements it, all of them promote it to acquire.
 *
 * On MSVC the weaker forms may emit stronger barriers than requested, which is
 * always safe. _ReadWriteBarrier is compiler only, which is sufficient on
 * x86-64 because the hardware already provides acquire and release.
 */

#if NTH_COMPILER_GCC || NTH_COMPILER_CLANG

    #define NTH_ATOMIC_DEFINE_LS(T, SUF, W, IT, ISUF, CT)                       \
        static inline T nth_atomic_load_##SUF(const volatile T *p) {            \
            T r;                                                                \
            __atomic_load(p, &r, __ATOMIC_SEQ_CST);                             \
            return r;                                                           \
        }                                                                       \
        static inline T nth_atomic_load_relaxed_##SUF(const volatile T *p) {    \
            T r;                                                                \
            __atomic_load(p, &r, __ATOMIC_RELAXED);                             \
            return r;                                                           \
        }                                                                       \
        static inline T nth_atomic_load_acquire_##SUF(const volatile T *p) {    \
            T r;                                                                \
            __atomic_load(p, &r, __ATOMIC_ACQUIRE);                             \
            return r;                                                           \
        }                                                                       \
        static inline void nth_atomic_store_##SUF(volatile T *p, T v) {         \
            __atomic_store(p, &v, __ATOMIC_SEQ_CST);                            \
        }                                                                       \
        static inline void nth_atomic_store_relaxed_##SUF(volatile T *p, T v) { \
            __atomic_store(p, &v, __ATOMIC_RELAXED);                            \
        }                                                                       \
        static inline void nth_atomic_store_release_##SUF(volatile T *p, T v) { \
            __atomic_store(p, &v, __ATOMIC_RELEASE);                            \
        }

    #define NTH_ATOMIC_DEFINE_RMW(T, SUF, ISUF, CT, UT)                          \
        static inline T nth_atomic_fetch_add_##SUF(volatile T *p, T v) {         \
            return __atomic_fetch_add(p, v, __ATOMIC_SEQ_CST);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_add_relaxed_##SUF(volatile T *p, T v) { \
            return __atomic_fetch_add(p, v, __ATOMIC_RELAXED);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_add_acq_rel_##SUF(volatile T *p, T v) { \
            return __atomic_fetch_add(p, v, __ATOMIC_ACQ_REL);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_sub_##SUF(volatile T *p, T v) {         \
            return __atomic_fetch_sub(p, v, __ATOMIC_SEQ_CST);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_sub_relaxed_##SUF(volatile T *p, T v) { \
            return __atomic_fetch_sub(p, v, __ATOMIC_RELAXED);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_sub_acq_rel_##SUF(volatile T *p, T v) { \
            return __atomic_fetch_sub(p, v, __ATOMIC_ACQ_REL);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_and_##SUF(volatile T *p, T v) {         \
            return __atomic_fetch_and(p, v, __ATOMIC_SEQ_CST);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_and_relaxed_##SUF(volatile T *p, T v) { \
            return __atomic_fetch_and(p, v, __ATOMIC_RELAXED);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_and_acq_rel_##SUF(volatile T *p, T v) { \
            return __atomic_fetch_and(p, v, __ATOMIC_ACQ_REL);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_or_##SUF(volatile T *p, T v) {          \
            return __atomic_fetch_or(p, v, __ATOMIC_SEQ_CST);                    \
        }                                                                        \
        static inline T nth_atomic_fetch_or_relaxed_##SUF(volatile T *p, T v) {  \
            return __atomic_fetch_or(p, v, __ATOMIC_RELAXED);                    \
        }                                                                        \
        static inline T nth_atomic_fetch_or_acq_rel_##SUF(volatile T *p, T v) {  \
            return __atomic_fetch_or(p, v, __ATOMIC_ACQ_REL);                    \
        }                                                                        \
        static inline T nth_atomic_fetch_xor_##SUF(volatile T *p, T v) {         \
            return __atomic_fetch_xor(p, v, __ATOMIC_SEQ_CST);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_xor_relaxed_##SUF(volatile T *p, T v) { \
            return __atomic_fetch_xor(p, v, __ATOMIC_RELAXED);                   \
        }                                                                        \
        static inline T nth_atomic_fetch_xor_acq_rel_##SUF(volatile T *p, T v) { \
            return __atomic_fetch_xor(p, v, __ATOMIC_ACQ_REL);                   \
        }

    #define NTH_ATOMIC_DEFINE_CAS(T, SUF, ISUF, CT)                     \
        static inline nth_b8 nth_atomic_cas_##SUF(                      \
                volatile T *p, T *expected, T desired) {                \
            return (nth_b8)__atomic_compare_exchange(                   \
                p, expected, &desired, 0,                               \
                __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST);                    \
        }                                                               \
        static inline nth_b8 nth_atomic_cas_relaxed_##SUF(              \
                volatile T *p, T *expected, T desired) {                \
            return (nth_b8)__atomic_compare_exchange(                   \
                p, expected, &desired, 0,                               \
                __ATOMIC_RELAXED, __ATOMIC_RELAXED);                    \
        }                                                               \
        static inline nth_b8 nth_atomic_cas_acq_rel_##SUF(              \
                volatile T *p, T *expected, T desired) {                \
            return (nth_b8)__atomic_compare_exchange(                   \
                p, expected, &desired, 0,                               \
                __ATOMIC_ACQ_REL, __ATOMIC_ACQUIRE);                    \
        }

#elif NTH_COMPILER_MSVC

    #define NTH_ATOMIC_DEFINE_LS(T, SUF, W, IT, ISUF, CT)                       \
        static inline T nth_atomic_load_##SUF(const volatile T *p) {            \
            IT b;                                                               \
            T r;                                                                \
            b = __iso_volatile_load##W((const volatile IT *)p);                 \
            _ReadWriteBarrier();                                                \
            memcpy(&r, &b, sizeof r);                                           \
            return r;                                                           \
        }                                                                       \
        static inline T nth_atomic_load_relaxed_##SUF(const volatile T *p) {    \
            IT b;                                                               \
            T r;                                                                \
            b = __iso_volatile_load##W((const volatile IT *)p);                 \
            memcpy(&r, &b, sizeof r);                                           \
            return r;                                                           \
        }                                                                       \
        static inline T nth_atomic_load_acquire_##SUF(const volatile T *p) {    \
            IT b;                                                               \
            T r;                                                                \
            b = __iso_volatile_load##W((const volatile IT *)p);                 \
            _ReadWriteBarrier();                                                \
            memcpy(&r, &b, sizeof r);                                           \
            return r;                                                           \
        }                                                                       \
        static inline void nth_atomic_store_##SUF(volatile T *p, T v) {         \
            IT b;                                                               \
            memcpy(&b, &v, sizeof b);                                           \
            (void)_InterlockedExchange##ISUF((volatile CT *)p, (CT)b);          \
        }                                                                       \
        static inline void nth_atomic_store_relaxed_##SUF(volatile T *p, T v) { \
            IT b;                                                               \
            memcpy(&b, &v, sizeof b);                                           \
            __iso_volatile_store##W((volatile IT *)p, b);                       \
        }                                                                       \
        static inline void nth_atomic_store_release_##SUF(volatile T *p, T v) { \
            IT b;                                                               \
            memcpy(&b, &v, sizeof b);                                           \
            _ReadWriteBarrier();                                                \
            __iso_volatile_store##W((volatile IT *)p, b);                       \
        }

    #define NTH_ATOMIC_DEFINE_RMW(T, SUF, ISUF, CT, UT)                          \
        static inline T nth_atomic_fetch_add_##SUF(volatile T *p, T v) {         \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedExchangeAdd##ISUF((volatile CT *)p, x);        \
        }                                                                        \
        static inline T nth_atomic_fetch_add_relaxed_##SUF(volatile T *p, T v) { \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedExchangeAdd##ISUF((volatile CT *)p, x);        \
        }                                                                        \
        static inline T nth_atomic_fetch_add_acq_rel_##SUF(volatile T *p, T v) { \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedExchangeAdd##ISUF((volatile CT *)p, x);        \
        }                                                                        \
        static inline T nth_atomic_fetch_sub_##SUF(volatile T *p, T v) {         \
            const CT x = (CT)(UT)(0 - (UT)v);                                    \
            return (T)_InterlockedExchangeAdd##ISUF((volatile CT *)p, x);        \
        }                                                                        \
        static inline T nth_atomic_fetch_sub_relaxed_##SUF(volatile T *p, T v) { \
            const CT x = (CT)(UT)(0 - (UT)v);                                    \
            return (T)_InterlockedExchangeAdd##ISUF((volatile CT *)p, x);        \
        }                                                                        \
        static inline T nth_atomic_fetch_sub_acq_rel_##SUF(volatile T *p, T v) { \
            const CT x = (CT)(UT)(0 - (UT)v);                                    \
            return (T)_InterlockedExchangeAdd##ISUF((volatile CT *)p, x);        \
        }                                                                        \
        static inline T nth_atomic_fetch_and_##SUF(volatile T *p, T v) {         \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedAnd##ISUF((volatile CT *)p, x);                \
        }                                                                        \
        static inline T nth_atomic_fetch_and_relaxed_##SUF(volatile T *p, T v) { \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedAnd##ISUF((volatile CT *)p, x);                \
        }                                                                        \
        static inline T nth_atomic_fetch_and_acq_rel_##SUF(volatile T *p, T v) { \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedAnd##ISUF((volatile CT *)p, x);                \
        }                                                                        \
        static inline T nth_atomic_fetch_or_##SUF(volatile T *p, T v) {          \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedOr##ISUF((volatile CT *)p, x);                 \
        }                                                                        \
        static inline T nth_atomic_fetch_or_relaxed_##SUF(volatile T *p, T v) {  \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedOr##ISUF((volatile CT *)p, x);                 \
        }                                                                        \
        static inline T nth_atomic_fetch_or_acq_rel_##SUF(volatile T *p, T v) {  \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedOr##ISUF((volatile CT *)p, x);                 \
        }                                                                        \
        static inline T nth_atomic_fetch_xor_##SUF(volatile T *p, T v) {         \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedXor##ISUF((volatile CT *)p, x);                \
        }                                                                        \
        static inline T nth_atomic_fetch_xor_relaxed_##SUF(volatile T *p, T v) { \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedXor##ISUF((volatile CT *)p, x);                \
        }                                                                        \
        static inline T nth_atomic_fetch_xor_acq_rel_##SUF(volatile T *p, T v) { \
            const CT x = (CT)v;                                                  \
            return (T)_InterlockedXor##ISUF((volatile CT *)p, x);                \
        }

    /* _InterlockedCompareExchange takes (destination, exchange, comparand) and
       returns the value destination held on entry, so the bool and the out
       parameter are both derived from it here. It is always sequentially
       consistent, hence the weaker orderings forwarding to the same call. */
    #define NTH_ATOMIC_DEFINE_CAS(T, SUF, ISUF, CT)                     \
        static inline nth_b8 nth_atomic_cas_##SUF(                      \
                volatile T *p, T *expected, T desired) {                \
            const CT comparand = (CT)*expected;                         \
            const CT seen = _InterlockedCompareExchange##ISUF(          \
                (volatile CT *)p, (CT)desired, comparand);              \
            if (seen == comparand)                                      \
                return NTH_TRUE;                                        \
            *expected = (T)seen;                                        \
            return NTH_FALSE;                                           \
        }                                                               \
        static inline nth_b8 nth_atomic_cas_relaxed_##SUF(              \
                volatile T *p, T *expected, T desired) {                \
            return nth_atomic_cas_##SUF(p, expected, desired);          \
        }                                                               \
        static inline nth_b8 nth_atomic_cas_acq_rel_##SUF(              \
                volatile T *p, T *expected, T desired) {                \
            return nth_atomic_cas_##SUF(p, expected, desired);          \
        }

#else
    #error "narthex: no atomic support known for this compiler"
#endif


NTH_ATOMIC_DEFINE_LS(nth_u8, u8, 8, __int8, 8, char)
NTH_ATOMIC_DEFINE_LS(nth_u16, u16, 16, __int16, 16, short)
NTH_ATOMIC_DEFINE_LS(nth_u32, u32, 32, __int32, , long)
NTH_ATOMIC_DEFINE_LS(nth_u64, u64, 64, __int64, 64, __int64)
NTH_ATOMIC_DEFINE_LS(nth_i8, i8, 8, __int8, 8, char)
NTH_ATOMIC_DEFINE_LS(nth_i16, i16, 16, __int16, 16, short)
NTH_ATOMIC_DEFINE_LS(nth_i32, i32, 32, __int32, , long)
NTH_ATOMIC_DEFINE_LS(nth_i64, i64, 64, __int64, 64, __int64)
NTH_ATOMIC_DEFINE_LS(nth_f32, f32, 32, __int32, , long)
NTH_ATOMIC_DEFINE_LS(nth_f64, f64, 64, __int64, 64, __int64)

NTH_ATOMIC_DEFINE_RMW(nth_u8, u8, 8, char, nth_u8)
NTH_ATOMIC_DEFINE_RMW(nth_u16, u16, 16, short, nth_u16)
NTH_ATOMIC_DEFINE_RMW(nth_u32, u32, , long, nth_u32)
NTH_ATOMIC_DEFINE_RMW(nth_u64, u64, 64, __int64, nth_u64)
NTH_ATOMIC_DEFINE_RMW(nth_i8, i8, 8, char, nth_u8)
NTH_ATOMIC_DEFINE_RMW(nth_i16, i16, 16, short, nth_u16)
NTH_ATOMIC_DEFINE_RMW(nth_i32, i32, , long, nth_u32)
NTH_ATOMIC_DEFINE_RMW(nth_i64, i64, 64, __int64, nth_u64)

NTH_ATOMIC_DEFINE_CAS(nth_u8, u8, 8, char)
NTH_ATOMIC_DEFINE_CAS(nth_u16, u16, 16, short)
NTH_ATOMIC_DEFINE_CAS(nth_u32, u32, , long)
NTH_ATOMIC_DEFINE_CAS(nth_u64, u64, 64, __int64)
NTH_ATOMIC_DEFINE_CAS(nth_i8, i8, 8, char)
NTH_ATOMIC_DEFINE_CAS(nth_i16, i16, 16, short)
NTH_ATOMIC_DEFINE_CAS(nth_i32, i32, , long)
NTH_ATOMIC_DEFINE_CAS(nth_i64, i64, 64, __int64)

#undef NTH_ATOMIC_DEFINE_LS
#undef NTH_ATOMIC_DEFINE_RMW
#undef NTH_ATOMIC_DEFINE_CAS


/* Type generic spellings: nth_atomic_load(p) picks nth_atomic_load_u32 and so
 * on from the type of *p. _Generic is C11 and has no C++ equivalent, so these
 * are conditional, and the library itself cannot use them in a public inline
 * function while it promises C99 to consumers. The suffixed names are always
 * available and stay the only spelling in C99 and C++. Test NTH_ATOMIC_GENERIC.
 *
 * The controlling expression is *(p), not p. It is never evaluated, and lvalue
 * conversion drops top level qualifiers, so one association per value type
 * matches T *, volatile T * and const volatile T * alike. Selecting on the
 * pointer would instead need an association per qualifier combination.
 */
#define NTH_ATOMIC_GENERIC 0

#if !defined(__cplusplus) && defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
    #undef  NTH_ATOMIC_GENERIC
    #define NTH_ATOMIC_GENERIC 1

/* Unlike the DEFINE macros above, these expand at the point of use, so they
   must stay defined rather than being undefined at the end of the header. */
#define NTH_ATOMIC_G_INT(op)        \
    nth_u8:  nth_atomic_##op##_u8,  \
    nth_u16: nth_atomic_##op##_u16, \
    nth_u32: nth_atomic_##op##_u32, \
    nth_u64: nth_atomic_##op##_u64, \
    nth_i8:  nth_atomic_##op##_i8,  \
    nth_i16: nth_atomic_##op##_i16, \
    nth_i32: nth_atomic_##op##_i32, \
    nth_i64: nth_atomic_##op##_i64

#define NTH_ATOMIC_G_ALL(op)        \
    NTH_ATOMIC_G_INT(op),           \
    nth_f32: nth_atomic_##op##_f32, \
    nth_f64: nth_atomic_##op##_f64

#define nth_atomic_load(p)          (_Generic(*(p), NTH_ATOMIC_G_ALL(load))(p))
#define nth_atomic_load_relaxed(p)  (_Generic(*(p), NTH_ATOMIC_G_ALL(load_relaxed))(p))
#define nth_atomic_load_acquire(p)  (_Generic(*(p), NTH_ATOMIC_G_ALL(load_acquire))(p))

#define nth_atomic_store(p, v)         (_Generic(*(p), NTH_ATOMIC_G_ALL(store))((p), (v)))
#define nth_atomic_store_relaxed(p, v) (_Generic(*(p), NTH_ATOMIC_G_ALL(store_relaxed))((p), (v)))
#define nth_atomic_store_release(p, v) (_Generic(*(p), NTH_ATOMIC_G_ALL(store_release))((p), (v)))

#define nth_atomic_fetch_add(p, v)         (_Generic(*(p), NTH_ATOMIC_G_INT(fetch_add))((p), (v)))
#define nth_atomic_fetch_add_relaxed(p, v) (_Generic(*(p), NTH_ATOMIC_G_INT(fetch_add_relaxed))((p), (v)))
#define nth_atomic_fetch_add_acq_rel(p, v) (_Generic(*(p), NTH_ATOMIC_G_INT(fetch_add_acq_rel))((p), (v)))

#define nth_atomic_fetch_sub(p, v)         (_Generic(*(p), NTH_ATOMIC_G_INT(fetch_sub))((p), (v)))
#define nth_atomic_fetch_sub_relaxed(p, v) (_Generic(*(p), NTH_ATOMIC_G_INT(fetch_sub_relaxed))((p), (v)))
#define nth_atomic_fetch_sub_acq_rel(p, v) (_Generic(*(p), NTH_ATOMIC_G_INT(fetch_sub_acq_rel))((p), (v)))

#define nth_atomic_fetch_and(p, v)         (_Generic(*(p), NTH_ATOMIC_G_INT(fetch_and))((p), (v)))
#define nth_atomic_fetch_and_relaxed(p, v) (_Generic(*(p), NTH_ATOMIC_G_INT(fetch_and_relaxed))((p), (v)))
#define nth_atomic_fetch_and_acq_rel(p, v) (_Generic(*(p), NTH_ATOMIC_G_INT(fetch_and_acq_rel))((p), (v)))

#define nth_atomic_fetch_or(p, v)          (_Generic(*(p), NTH_ATOMIC_G_INT(fetch_or))((p), (v)))
#define nth_atomic_fetch_or_relaxed(p, v)  (_Generic(*(p), NTH_ATOMIC_G_INT(fetch_or_relaxed))((p), (v)))
#define nth_atomic_fetch_or_acq_rel(p, v)  (_Generic(*(p), NTH_ATOMIC_G_INT(fetch_or_acq_rel))((p), (v)))

#define nth_atomic_fetch_xor(p, v)         (_Generic(*(p), NTH_ATOMIC_G_INT(fetch_xor))((p), (v)))
#define nth_atomic_fetch_xor_relaxed(p, v) (_Generic(*(p), NTH_ATOMIC_G_INT(fetch_xor_relaxed))((p), (v)))
#define nth_atomic_fetch_xor_acq_rel(p, v) (_Generic(*(p), NTH_ATOMIC_G_INT(fetch_xor_acq_rel))((p), (v)))

#define nth_atomic_cas(p, e, d)         (_Generic(*(p), NTH_ATOMIC_G_INT(cas))((p), (e), (d)))
#define nth_atomic_cas_relaxed(p, e, d) (_Generic(*(p), NTH_ATOMIC_G_INT(cas_relaxed))((p), (e), (d)))
#define nth_atomic_cas_acq_rel(p, e, d) (_Generic(*(p), NTH_ATOMIC_G_INT(cas_acq_rel))((p), (e), (d)))

#endif /* _Generic */


#ifdef __cplusplus
}
#endif

#endif /* NTH_INL_ATOMIC_H */
