add_executable(unit_mem_align unit_align.c)
target_link_libraries(unit_mem_align PRIVATE narthex::narthex)
target_include_directories(unit_mem_align PRIVATE ${NTH_TEST_INCLUDE})
add_test(NAME mem/align COMMAND unit_mem_align)
set_tests_properties(mem/align PROPERTIES LABELS "unit")

add_executable(unit_mem_arena unit_arena.c)
target_link_libraries(unit_mem_arena PRIVATE narthex::narthex)
target_include_directories(unit_mem_arena PRIVATE ${NTH_TEST_INCLUDE})
add_test(NAME mem/arena COMMAND unit_mem_arena)
set_tests_properties(mem/arena PROPERTIES LABELS "unit")

add_executable(unit_mem_dyn_arena unit_dyn_arena.c)
target_link_libraries(unit_mem_dyn_arena PRIVATE narthex::narthex)
target_include_directories(unit_mem_dyn_arena PRIVATE ${NTH_TEST_INCLUDE})
add_test(NAME mem/dyn_arena COMMAND unit_mem_dyn_arena)
set_tests_properties(mem/dyn_arena PROPERTIES LABELS "unit")

add_executable(unit_free_list unit_free_list.c)
target_link_libraries(unit_free_list PRIVATE narthex::narthex)
target_include_directories(unit_free_list PRIVATE ${NTH_TEST_INCLUDE})
add_test(NAME mem/free_list COMMAND unit_free_list)
set_tests_properties(mem/free_list PROPERTIES LABELS "unit")
