set(NTH_ALL_MODULES "" CACHE INTERNAL "All registered modules")

function(nth_register name)
    cmake_parse_arguments(C "" "DEFAULT;DESCRIPTION" "DEPENDS" ${ARGN})

    if(NOT DEFINED C_DEFAULT)
        message(FATAL_ERROR "nth_register(${name}): DEFAULT is required")
    endif()

    list(APPEND NTH_ALL_MODULES ${name})
    set(NTH_ALL_MODULES "${NTH_ALL_MODULES}" CACHE INTERNAL "")

    set(NTH_${name}_DEPS "${C_DEPENDS}" CACHE INTERNAL "")
    option(NTH_ENABLE_${name} "${C_DESCRIPTION}" ${C_DEFAULT})
endfunction()

function(nth_resolve_modules)
    set(changed TRUE)
    while(changed)
        set(changed FALSE)
        foreach(c IN LISTS NTH_ALL_MODULES)
            if(NTH_ENABLE_${c})
                foreach(dep IN LISTS NTH_${c}_DEPS)
                    if(NOT DEFINED NTH_ENABLE_${dep})
                        message(FATAL_ERROR
                            "Module '${c}' depends on unknown module '${dep}'")
                    endif()
                    if(NOT NTH_ENABLE_${dep})
                        message(STATUS
                            "Narthex: enabling '${dep}' (required by '${c}')")
                        set(NTH_ENABLE_${dep} ON CACHE BOOL "" FORCE)
                        set(changed TRUE)
                    endif()
                endforeach()
            endif()
        endforeach()
    endwhile()
endfunction()

function(nth_print_summary)
    message(STATUS "")
    message(STATUS "Narthex modules:")
    foreach(c IN LISTS NTH_ALL_MODULES)
        if(NTH_ENABLE_${c})
            message(STATUS "  [x] ${c}")
        else()
            message(STATUS "  [ ] ${c}")
        endif()
    endforeach()
    message(STATUS "")
endfunction()